match_config:
  time_limit: 30.0
  mode:
    type: KingOfTheHill
    capture_points:
      -
        x: 0.0
        y: 0.0
        radius: 5.0
        capture_speed: 0.1
        team: 0
    point_limit: 15.0

spawn_config:
  teams:
    -
      name: Red
      color: [255, 0, 0]
      controller:
        type: SequenceControl
        controllers:
          - type: RadioPosition
          - type: DiffDriveCapturable
          - type: TankNaiveShoot
    -
      name: Blue
      color: [0, 0, 255]
      controller:
        type: SequenceControl
        controllers:
          - type: RadioPosition
          - type: DiffDriveCapturable
          - type: TankNaiveShoot
  spawns:
    -
      x: 10.0
      y: 0.0
      yaw: 3.14
      controller:
        type: TeamController
        name: Red
      team: 0
    -
      x: -10.0
      y: 0.0
      yaw: 0
      team: 0
      controller:
        type: TeamController
        name: Red

    -
      x: 0.0
      y: -10.0
      #  yaw: 1.5708
      yaw: 0.0
      team: 1
      radio_config:
        channel_min: 10
        channel_max: 10
      controller:
        type: TeamController
        name: Blue

    -
      x: 0.0
      y: 10.0
      yaw: -1.5708
      team: 1
      radio_config:
        channel_min: 10
        channel_max: 10
      controller:
        type: TeamController
        name: Blue
