match_config:
  mode:
    type: KingOfTheHill
    capture_points:
      -
        x: 0.0
        y: 0.0
        radius: 5.0
        capture_speed: 0.1
    point_limit: 0.1

spawn_config:
  teams:
    -
      name: Player
      color: [255, 0, 0]
      controller: 
        type: Wasm
        reload: true
        path: "<no path specified>"
        fuel_per_update: 1000000
    -
      name: Blue
      color: [0, 0, 255]
  spawns:
    -
      x: 10.0
      y: 0.0
      yaw: 2.5
      controller:
        type: TeamController
        name: Player
      team: 0
