[package]
name = "battleground_construct"
version = "0.1.0"
edition = "2021"


[dependencies]
engine = { path = "../engine" }
battleground_vehicle_control = { path = "../battleground_vehicle_control" }
libloading = "0.7.4"
cgmath = "0.18.0"

[dev-dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"

