[workspace]

members = [
    "engine",
    "battleground_construct",
    "battleground_viewer",
    "battleground_unit_control",
    "unit_control_example",
    "unit_control_wasm",
    "unit_control_builtin",
]

[profile.release]
opt-level = 3
debug = true
