[workspace]

members = [
    "engine",
    "battleground_construct",
    "battleground_viewer",
    "example_driving_ai",
    "battleground_vehicle_control",
    "vehicle_control_wasm",
]

[profile.release]
opt-level = 3
