[package]
name = "battleground_viewer"
version = "0.1.0"
edition = "2021"


[dependencies]
engine = { path = "../engine" }
battleground_construct = { path = "../battleground_construct" }
#three-d = {version = "0.14.0", features=["egui-gui"]}
three-d = {version = "0.15.0", features=["egui-gui"], path = "../../../asny-three-d" }
#three-d = {version = "0.15.0", features=["egui-gui"], git = "https://github.com/iwanders/asny-three-d", branch = "orbit-control-improvements"  }
#three-d = {version = "0.15.0", features=["egui-gui"], git = "https://github.com/iwanders/asny-three-d", rev = "f69504e3da5254e1087a0af7a8a8e2f055b16afb"  }
rand = "0.8.5"
rand_distr = "0.4.3"
