[package]
name = "unit_control_example"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
battleground_unit_control = { path = "../battleground_unit_control", features=["wasm-interface"] }
