[package]
name = "battleground_unit_control"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
log = "0.4.17"
engine = {path="../engine/", optional=true}

[features]
default = []
register_interface = ["engine"]
