match_config:
  mode:
    type: KingOfTheHill
    capture_points:
      -
        x: 0.0
        y: 0.0
        radius: 10.0
        capture_speed: 0.1
        team: 0
    point_limit: 5.0

spawn_config:
  teams:
    -
      name: Red
      color: [255, 0, 0]
    -
      name: Blue
      color: [0, 0, 255]
  spawns:
    -
      x: 2.0
      y: 0.0
      yaw: 3.14
      controller:
        type: SwivelShoot
      team: 0
    -
      x: -2.0
      y: 0.0
      yaw: 0
      team: 0
      #controller: 
      #  type: Wasm
      #  module: "../target/wasm32-unknown-unknown/release/example_driving_ai.wasm"

    -
      x: 0.0
      y: -2.0
      yaw: 1.5708
      team: 1

    -
      x: 0.0
      y: 2.0
      yaw: -1.5708
      team: 1
