  
spawn_config:
  teams:
    -
      name: Alpha
    -
      name: Bravo
  spawns:
    -
      x: 2.0
      y: 0.0
      yaw: 3.14
    -
      x: -2.0
      y: 0.0
      yaw: 0

    -
      x: 0.0
      y: -2.0
      yaw: 1.5708

    -
      x: 0.0
      y: 2.0
      yaw: -1.5708
