name: Rust Checks
run-name: "${{ github.ref }} by @${{ github.actor }}"

on:
  push:
    branches:
      - master
      - pipeline-test
  pull_request:
    branches:
      - master
  workflow_dispatch:


env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  ubuntu-native:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Rust install
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
          sh ./rustup.sh --profile minimal -y
      - name: Format
        # https://github.com/rust-lang/rustfmt#checking-style-on-a-ci-server
        run: cargo fmt  --all -- --check
      - name: Clippy
        run: cargo clippy --release -- --no-deps
      - name: Build
        run: cargo build --release --features unit_control_wasm
      - name: Test
        run: cargo test --release --features unit_control_wasm

  web-wasmpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rust install
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
          sh ./rustup.sh --profile minimal -y -t wasm32-unknown-unknown
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Change Dir
        run: |
          cd battleground_viewer
      - name: Build
        run: |
          cat /home/runner/work/battleground_construct/battleground_construct/Cargo.toml
          wasm-pack build --release --target web --out-name web
      - name: Clippy
        run: |
          cargo clippy --release --target wasm32-unknown-unknown -- --no-deps
          
